# Generated by Django 4.2.6 on 2023-10-23 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housenumber', models.IntegerField()),
                ('flatnumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=255)),
                ('bookimg', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('number_of_pages', models.IntegerField()),
                ('year', models.IntegerField()),
                ('count', models.IntegerField()),
                ('description', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.author')),
            ],
        ),
        migrations.CreateModel(
            name='Cardholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholdername', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cardtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardtypename', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryfirstname', models.CharField(max_length=255)),
                ('deliverysurname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=70)),
                ('telephonenumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Deliveryuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryfirstname', models.CharField(max_length=255)),
                ('deliverysurname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=70)),
                ('telephonenumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genrename', models.CharField(max_length=255)),
                ('genreimg', models.ImageField(upload_to='photos/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Orderstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderstatus', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Paymentstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paystatus', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Publishing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardnumber', models.IntegerField()),
                ('dateissue', models.DateTimeField()),
                ('cardyear', models.IntegerField()),
                ('cvc', models.IntegerField()),
                ('cardholder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.cardholder')),
                ('cardtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.cardtype')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countofbook', models.IntegerField()),
                ('departuredate', models.DateTimeField()),
                ('arrivaldate', models.DateTimeField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.book')),
                ('customerusers', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.customeruser')),
                ('deliveryusers', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.deliveryuser')),
                ('orderstatus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.orderstatus')),
                ('toaddress', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.address')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.usercard')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.order')),
                ('paymentstatus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.paymentstatus')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='publishing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.publishing'),
        ),
        migrations.AddField(
            model_name='address',
            name='cityname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.city'),
        ),
        migrations.AddField(
            model_name='address',
            name='streetname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.street'),
        ),
    ]
