# Generated by Django 4.2.5 on 2023-11-11 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_rename_deliveryfirstname_customeruser_customfirstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizzaname', models.CharField(max_length=255)),
                ('pizzaimg', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('cost', models.IntegerField(null=True)),
                ('description', models.TextField()),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='book.menu')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='order',
            name='book',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AddField(
            model_name='order',
            name='pizza',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='book.pizza'),
            preserve_default=False,
        ),
    ]
