# Generated by Django 4.2.5 on 2023-11-16 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_street_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='menu_name',
            new_name='name',
        ),
    ]
